
#ifndef FLSTST_MEMMAP_H
#define FLSTST_MEMMAP_H


/*******************************************************************************
**                      Revision Control History                              **
*******************************************************************************/

#define FLSTST_MEMMAP_H_AR_MAJOR_VERSION 4U
#define FLSTST_MEMMAP_H_AR_MINOR_VERSION 2U
#define FLSTST_MEMMAP_H_AR_PATCH_VERSION 4U
#define FLSTST_MEMMAP_H_SW_MAJOR_VERSION 1U
#define FLSTST_MEMMAP_H_SW_MINOR_VERSION 0U
#define FLSTST_MEMMAP_H_SW_PATCH_VERSION 0U

/*=============================[M A C R O S]==================================*/
#if defined (START_WITH_IF)


#elif defined (FLSTST_START_SEC_CODE)
#undef      FLSTST_START_SEC_CODE
#define START_SEC_CODE
#elif defined (FLSTST_STOP_SEC_CODE)
#undef      FLSTST_STOP_SEC_CODE
#define STOP_SEC_CODE

#elif defined (FLSTST_START_SEC_CODE_FAST)
#undef      FLSTST_START_SEC_CODE_FAST
#define START_SEC_CODE_FAST
#elif defined (FLSTST_STOP_SEC_CODE_FAST)
#undef      FLSTST_STOP_SEC_CODE_FAST
#define STOP_SEC_CODE_FAST

#elif defined (FLSTST_START_SEC_VAR_NOINIT_BOOLEAN)
#undef      FLSTST_START_SEC_VAR_NOINIT_BOOLEAN
#define START_SEC_VAR_NOINIT_BOOLEAN
#elif defined (FLSTST_STOP_SEC_VAR_NOINIT_BOOLEAN)
#undef      FLSTST_STOP_SEC_VAR_NOINIT_BOOLEAN
#define STOP_SEC_VAR_NOINIT_BOOLEAN

#elif defined (FLSTST_START_SEC_VAR_NOINIT_8BIT)
#undef      FLSTST_START_SEC_VAR_NOINIT_8BIT
#define START_SEC_VAR_NOINIT_8BIT
#elif defined (FLSTST_STOP_SEC_VAR_NOINIT_8BIT)
#undef      FLSTST_STOP_SEC_VAR_NOINIT_8BIT
#define STOP_SEC_VAR_NOINIT_8BIT

#elif defined (FLSTST_START_SEC_VAR_NOINIT_16BIT)
#undef      FLSTST_START_SEC_VAR_NOINIT_16BIT
#define START_SEC_VAR_NOINIT_16BIT
#elif defined (FLSTST_STOP_SEC_VAR_NOINIT_16BIT)
#undef      FLSTST_STOP_SEC_VAR_NOINIT_16BIT
#define STOP_SEC_VAR_NOINIT_16BIT

#elif defined (FLSTST_START_SEC_VAR_NOINIT_32BIT)
#undef      FLSTST_START_SEC_VAR_NOINIT_32BIT
#define START_SEC_VAR_NOINIT_32BIT
#elif defined (FLSTST_STOP_SEC_VAR_NOINIT_32BIT)
#undef      FLSTST_STOP_SEC_VAR_NOINIT_32BIT
#define STOP_SEC_VAR_NOINIT_32BIT

#elif defined (FLSTST_START_SEC_VAR_NOINIT_UNSPECIFIED)
#undef      FLSTST_START_SEC_VAR_NOINIT_UNSPECIFIED
#define START_SEC_VAR_NOINIT_UNSPECIFIED
#elif defined (FLSTST_STOP_SEC_VAR_NOINIT_UNSPECIFIED)
#undef      FLSTST_STOP_SEC_VAR_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR_NOINIT_UNSPECIFIED

#elif defined (FLSTST_START_SEC_VAR_POWER_ON_INIT_BOOLEAN)
#undef      FLSTST_START_SEC_VAR_POWER_ON_INIT_BOOLEAN
#define START_SEC_VAR_POWER_ON_INIT_BOOLEAN
#elif defined (FLSTST_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN)
#undef      FLSTST_STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN
#define STOP_SEC_VAR_POWER_ON_INIT_BOOLEAN

#elif defined (FLSTST_START_SEC_VAR_POWER_ON_INIT_8BIT)
#undef      FLSTST_START_SEC_VAR_POWER_ON_INIT_8BIT
#define START_SEC_VAR_POWER_ON_INIT_8BIT
#elif defined (FLSTST_STOP_SEC_VAR_POWER_ON_INIT_8BIT)
#undef      FLSTST_STOP_SEC_VAR_POWER_ON_INIT_8BIT
#define STOP_SEC_VAR_POWER_ON_INIT_8BIT

#elif defined (FLSTST_START_SEC_VAR_POWER_ON_INIT_16BIT)
#undef      FLSTST_START_SEC_VAR_POWER_ON_INIT_16BIT
#define START_SEC_VAR_POWER_ON_INIT_16BIT
#elif defined (FLSTST_STOP_SEC_VAR_POWER_ON_INIT_16BIT)
#undef      FLSTST_STOP_SEC_VAR_POWER_ON_INIT_16BIT
#define STOP_SEC_VAR_POWER_ON_INIT_16BIT

#elif defined (FLSTST_START_SEC_VAR_POWER_ON_INIT_32BIT)
#undef      FLSTST_START_SEC_VAR_POWER_ON_INIT_32BIT
#define START_SEC_VAR_POWER_ON_INIT_32BIT
#elif defined (FLSTST_STOP_SEC_VAR_POWER_ON_INIT_32BIT)
#undef      FLSTST_STOP_SEC_VAR_POWER_ON_INIT_32BIT
#define STOP_SEC_VAR_POWER_ON_INIT_32BIT

#elif defined (FLSTST_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
#undef      FLSTST_START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
#define START_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
#elif defined (FLSTST_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED)
#undef      FLSTST_STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED
#define STOP_SEC_VAR_POWER_ON_INIT_UNSPECIFIED

#elif defined (FLSTST_START_SEC_VAR_BOOLEAN)
#undef      FLSTST_START_SEC_VAR_BOOLEAN
#define START_SEC_VAR_BOOLEAN
#elif defined (FLSTST_STOP_SEC_VAR_BOOLEAN)
#undef      FLSTST_STOP_SEC_VAR_BOOLEAN
#define STOP_SEC_VAR_BOOLEAN

#elif defined (FLSTST_START_SEC_VAR_8BIT)
#undef      FLSTST_START_SEC_VAR_8BIT
#define START_SEC_VAR_8BIT
#elif defined (FLSTST_STOP_SEC_VAR_8BIT)
#undef      FLSTST_STOP_SEC_VAR_8BIT
#define STOP_SEC_VAR_8BIT

#elif defined (FLSTST_START_SEC_VAR_16BIT)
#undef      FLSTST_START_SEC_VAR_16BIT
#define START_SEC_VAR_16BIT
#elif defined (FLSTST_STOP_SEC_VAR_16BIT)
#undef      FLSTST_STOP_SEC_VAR_16BIT
#define STOP_SEC_VAR_16BIT

#elif defined (FLSTST_START_SEC_VAR_32BIT)
#undef      FLSTST_START_SEC_VAR_32BIT
#define START_SEC_VAR_32BIT
#elif defined (FLSTST_STOP_SEC_VAR_32BIT)
#undef      FLSTST_STOP_SEC_VAR_32BIT
#define STOP_SEC_VAR_32BIT

#elif defined (FLSTST_START_SEC_VAR_UNSPECIFIED)
#undef      FLSTST_START_SEC_VAR_UNSPECIFIED
#define START_SEC_VAR_UNSPECIFIED
#elif defined (FLSTST_STOP_SEC_VAR_UNSPECIFIED)
#undef      FLSTST_STOP_SEC_VAR_UNSPECIFIED
#define STOP_SEC_VAR_UNSPECIFIED


#elif defined (FLSTST_START_SEC_VAR_FAST_NOINIT_BOOLEAN)
#undef      FLSTST_START_SEC_VAR_FAST_NOINIT_BOOLEAN
#define START_SEC_VAR_FAST_NOINIT_BOOLEAN
#elif defined (FLSTST_STOP_SEC_VAR_FAST_NOINIT_BOOLEAN)
#undef      FLSTST_STOP_SEC_VAR_FAST_NOINIT_BOOLEAN
#define STOP_SEC_VAR_FAST_NOINIT_BOOLEAN

#elif defined (FLSTST_START_SEC_VAR_FAST_NOINIT_8BIT)
#undef      FLSTST_START_SEC_VAR_FAST_NOINIT_8BIT
#define START_SEC_VAR_FAST_NOINIT_8BIT
#elif defined (FLSTST_STOP_SEC_VAR_FAST_NOINIT_8BIT)
#undef      FLSTST_STOP_SEC_VAR_FAST_NOINIT_8BIT
#define STOP_SEC_VAR_FAST_NOINIT_8BIT

#elif defined (FLSTST_START_SEC_VAR_FAST_NOINIT_16BIT)
#undef      FLSTST_START_SEC_VAR_FAST_NOINIT_16BIT
#define START_SEC_VAR_FAST_NOINIT_16BIT
#elif defined (FLSTST_STOP_SEC_VAR_FAST_NOINIT_16BIT)
#undef      FLSTST_STOP_SEC_VAR_FAST_NOINIT_16BIT
#define STOP_SEC_VAR_FAST_NOINIT_16BIT

#elif defined (FLSTST_START_SEC_VAR_FAST_NOINIT_32BIT)
#undef      FLSTST_START_SEC_VAR_FAST_NOINIT_32BIT
#define START_SEC_VAR_FAST_NOINIT_32BIT
#elif defined (FLSTST_STOP_SEC_VAR_FAST_NOINIT_32BIT)
#undef      FLSTST_STOP_SEC_VAR_FAST_NOINIT_32BIT
#define STOP_SEC_VAR_FAST_NOINIT_32BIT

#elif defined (FLSTST_START_SEC_VAR_FAST_NOINIT_UNSPECIFIED)
#undef      FLSTST_START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#define START_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#elif defined (FLSTST_STOP_SEC_VAR_FAST_NOINIT_UNSPECIFIED)
#undef      FLSTST_STOP_SEC_VAR_FAST_NOINIT_UNSPECIFIED
#define STOP_SEC_VAR_FAST_NOINIT_UNSPECIFIED

#elif defined (FLSTST_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN)
#undef      FLSTST_START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
#define START_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
#elif defined (FLSTST_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN)
#undef      FLSTST_STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN
#define STOP_SEC_VAR_FAST_POWER_ON_INIT_BOOLEAN

#elif defined (FLSTST_START_SEC_VAR_FAST_POWER_ON_INIT_8BIT)
#undef      FLSTST_START_SEC_VAR_FAST_POWER_ON_INIT_8BIT
#define START_SEC_VAR_FAST_POWER_ON_INIT_8BIT
#elif defined (FLSTST_STOP_SEC_VAR_FAST_POWER_ON_INIT_8BIT)
#undef      FLSTST_STOP_SEC_VAR_FAST_POWER_ON_INIT_8BIT
#define STOP_SEC_VAR_FAST_POWER_ON_INIT_8BIT

#elif defined (FLSTST_START_SEC_VAR_FAST_POWER_ON_INIT_16BIT)
#undef      FLSTST_START_SEC_VAR_FAST_POWER_ON_INIT_16BIT
#define START_SEC_VAR_FAST_POWER_ON_INIT_16BIT
#elif defined (FLSTST_STOP_SEC_VAR_FAST_POWER_ON_INIT_16BIT)
#undef      FLSTST_STOP_SEC_VAR_FAST_POWER_ON_INIT_16BIT
#define STOP_SEC_VAR_FAST_POWER_ON_INIT_16BIT

#elif defined (FLSTST_START_SEC_VAR_FAST_POWER_ON_INIT_32BIT)
#undef      FLSTST_START_SEC_VAR_FAST_POWER_ON_INIT_32BIT
#define START_SEC_VAR_FAST_POWER_ON_INIT_32BIT
#elif defined (FLSTST_STOP_SEC_VAR_FAST_POWER_ON_INIT_32BIT)
#undef      FLSTST_STOP_SEC_VAR_FAST_POWER_ON_INIT_32BIT
#define STOP_SEC_VAR_FAST_POWER_ON_INIT_32BIT

#elif defined (FLSTST_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED)
#undef      FLSTST_START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
#define START_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
#elif defined (FLSTST_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED)
#undef      FLSTST_STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED
#define STOP_SEC_VAR_FAST_POWER_ON_INIT_UNSPECIFIED

#elif defined (FLSTST_START_SEC_VAR_FAST_BOOLEAN)
#undef      FLSTST_START_SEC_VAR_FAST_BOOLEAN
#define START_SEC_VAR_FAST_BOOLEAN
#elif defined (FLSTST_STOP_SEC_VAR_FAST_BOOLEAN)
#undef      FLSTST_STOP_SEC_VAR_FAST_BOOLEAN
#define STOP_SEC_VAR_FAST_BOOLEAN

#elif defined (FLSTST_START_SEC_VAR_FAST_8BIT)
#undef      FLSTST_START_SEC_VAR_FAST_8BIT
#define START_SEC_VAR_FAST_8BIT
#elif defined (FLSTST_STOP_SEC_VAR_FAST_8BIT)
#undef      FLSTST_STOP_SEC_VAR_FAST_8BIT
#define STOP_SEC_VAR_FAST_8BIT

#elif defined (FLSTST_START_SEC_VAR_FAST_16BIT)
#undef      FLSTST_START_SEC_VAR_FAST_16BIT
#define START_SEC_VAR_FAST_16BIT
#elif defined (FLSTST_STOP_SEC_VAR_FAST_16BIT)
#undef      FLSTST_STOP_SEC_VAR_FAST_16BIT
#define STOP_SEC_VAR_FAST_16BIT

#elif defined (FLSTST_START_SEC_VAR_FAST_32BIT)
#undef      FLSTST_START_SEC_VAR_FAST_32BIT
#define START_SEC_VAR_FAST_32BIT
#elif defined (FLSTST_STOP_SEC_VAR_FAST_32BIT)
#undef      FLSTST_STOP_SEC_VAR_FAST_32BIT
#define STOP_SEC_VAR_FAST_32BIT

#elif defined (FLSTST_START_SEC_VAR_FAST_UNSPECIFIED)
#undef      FLSTST_START_SEC_VAR_FAST_UNSPECIFIED
#define START_SEC_VAR_FAST_UNSPECIFIED
#elif defined (FLSTST_STOP_SEC_VAR_FAST_UNSPECIFIED)
#undef      FLSTST_STOP_SEC_VAR_FAST_UNSPECIFIED
#define STOP_SEC_VAR_FAST_UNSPECIFIED

#elif defined (FLSTST_START_SEC_CONST_BOOLEAN)
#undef      FLSTST_START_SEC_CONST_BOOLEAN
#define START_SEC_CONST_BOOLEAN
#elif defined (FLSTST_STOP_SEC_CONST_BOOLEAN)
#undef      FLSTST_STOP_SEC_CONST_BOOLEAN
#define STOP_SEC_CONST_BOOLEAN

#elif defined (FLSTST_START_SEC_CONST_8BIT)
#undef      FLSTST_START_SEC_CONST_8BIT
#define START_SEC_CONST_8BIT
#elif defined (FLSTST_STOP_SEC_CONST_8BIT)
#undef      FLSTST_STOP_SEC_CONST_8BIT
#define STOP_SEC_CONST_8BIT

#elif defined (FLSTST_START_SEC_CONST_16BIT)
#undef      FLSTST_START_SEC_CONST_16BIT
#define START_SEC_CONST_16BIT
#elif defined (FLSTST_STOP_SEC_CONST_16BIT)
#undef      FLSTST_STOP_SEC_CONST_16BIT
#define STOP_SEC_CONST_16BIT

#elif defined (FLSTST_START_SEC_CONST_32BIT)
#undef      FLSTST_START_SEC_CONST_32BIT
#define START_SEC_CONST_32BIT
#elif defined (FLSTST_STOP_SEC_CONST_32BIT)
#undef      FLSTST_STOP_SEC_CONST_32BIT
#define STOP_SEC_CONST_32BIT

#elif defined (FLSTST_START_SEC_CONST_UNSPECIFIED)
#undef      FLSTST_START_SEC_CONST_UNSPECIFIED
#define START_SEC_CONST_UNSPECIFIED
#elif defined (FLSTST_STOP_SEC_CONST_UNSPECIFIED)
#undef      FLSTST_STOP_SEC_CONST_UNSPECIFIED
#define STOP_SEC_CONST_UNSPECIFIED

#elif defined (FLSTST_START_SEC_CONST_FAST_BOOLEAN)
#undef      FLSTST_START_SEC_CONST_FAST_BOOLEAN
#define START_SEC_CONST_FAST_BOOLEAN
#elif defined (FLSTST_STOP_SEC_CONST_FAST_BOOLEAN)
#undef      FLSTST_STOP_SEC_CONST_FAST_BOOLEAN
#define STOP_SEC_CONST_FAST_BOOLEAN

#elif defined (FLSTST_START_SEC_CONST_FAST_8BIT)
#undef      FLSTST_START_SEC_CONST_FAST_8BIT
#define START_SEC_CONST_FAST_8BIT
#elif defined (FLSTST_STOP_SEC_CONST_FAST_8BIT)
#undef      FLSTST_STOP_SEC_CONST_FAST_8BIT
#define STOP_SEC_CONST_FAST_8BIT

#elif defined (FLSTST_START_SEC_CONST_FAST_16BIT)
#undef      FLSTST_START_SEC_CONST_FAST_16BIT
#define START_SEC_CONST_FAST_16BIT
#elif defined (FLSTST_STOP_SEC_CONST_FAST_16BIT)
#undef      FLSTST_STOP_SEC_CONST_FAST_16BIT
#define STOP_SEC_CONST_FAST_16BIT

#elif defined (FLSTST_START_SEC_CONST_FAST_32BIT)
#undef      FLSTST_START_SEC_CONST_FAST_32BIT
#define START_SEC_CONST_FAST_32BIT
#elif defined (FLSTST_STOP_SEC_CONST_FAST_32BIT)
#undef      FLSTST_STOP_SEC_CONST_FAST_32BIT
#define STOP_SEC_CONST_FAST_32BIT

#elif defined (FLSTST_START_SEC_CONST_FAST_UNSPECIFIED)
#undef      FLSTST_START_SEC_CONST_FAST_UNSPECIFIED
#define START_SEC_CONST_FAST_UNSPECIFIED
#elif defined (FLSTST_STOP_SEC_CONST_FAST_UNSPECIFIED)
#undef      FLSTST_STOP_SEC_CONST_FAST_UNSPECIFIED
#define STOP_SEC_CONST_FAST_UNSPECIFIED

#elif defined (FLSTST_START_CONST_PBCFG)
#undef      FLSTST_START_CONST_PBCFG
#define START_CONST_PBCFG
#elif defined (FLSTST_STOP_CONST_PBCFG)
#undef      FLSTST_STOP_CONST_PBCFG
#define STOP_CONST_PBCFG

#elif defined (FLSTST_START_CONST_PBCFG_ROOT)
#undef      FLSTST_START_CONST_PBCFG_ROOT
#define START_CONST_PBCFG_ROOT
#elif defined (FLSTST_STOP_CONST_PBCFG_ROOT)
#undef      FLSTST_STOP_CONST_PBCFG_ROOT
#define STOP_CONST_PBCFG_ROOT

#endif /* START_WITH_IF */

#include "MemMap.h"

#endif