/*******************************************************************************
** xzq: this part is deigned by munual,not generated by tools, and not autosar**
*******************************************************************************/

/*******************************************************************************
**                      Include                                               **
*******************************************************************************/
#include "Fls.h"
#include "Fee.h"
#include "NvM.h"
#include "Rte_Nvm.h"
/*******************************************************************************
**                      Imported Compiler Switch Check                        **
*******************************************************************************/


/*******************************************************************************
**                       Version  Check                                       **
*******************************************************************************/


/*******************************************************************************
**                      Private Variable Definitions                          **
*******************************************************************************/


/*******************************************************************************
**                      Private Type Definitions                              **
*******************************************************************************/



/*******************************************************************************
**                      Private Function Declarations                         **
*******************************************************************************/



/*******************************************************************************
**                      Global Variable Definitions                           **
*******************************************************************************/



/*******************************************************************************
**                      Global Function Definitions                           **
*******************************************************************************/
/* Test code main function to test NVM function */
uint8 Test_Nvm_Cmd;
void TestCode_NvmFunction(void)
{
	uint8 index;
	for(index=0;index<100;index++)
	{
		NvMBlockRamBuffer3[index] = index;
	}
	if(Test_Nvm_Cmd == 0xaa)
	{
		Test_Nvm_Cmd = 0x0;
		NvM_WriteBlock(NvMBlock_All_EventEntry,NvMBlockRamBuffer3);
	}
}
/* Read all block with readall attribute */
uint8 NvM_ReadAll_Immediately(void)
{
	NvM_ReadAll();
	NvM_RequestResultType RequestResultPtr = NVM_REQ_NOT_OK;
	uint16 NVM_OP_USE_TIME = 0u;
	SuspendAllInterrupts();
	do
	{
		NVM_OP_USE_TIME++;
		NvM_MainFunction();
		Fee_MainFunction();
		Fls_MainFunction();
		NvM_GetErrorStatus(0, &RequestResultPtr);
		if (NVM_OP_USE_TIME == 500)
			break;
	} while (RequestResultPtr == NVM_REQ_PENDING);
	ResumeAllInterrupts();
	if (NVM_OP_USE_TIME == 500u)
	{
		return E_NOT_OK;
	}
	else
	{
		return E_OK;
	}
}
/*******************************************************************************
**                      Private Function Definitions                          **
*******************************************************************************/
/*=======[E N D   O F   F I L E]==============================================*/
