#ifndef RTE_COM_H
#define RTE_COM_H
/*******************************************************************************
** xzq: this part is deigned by munual,not generated by tools, and not autosar**
*******************************************************************************/

/*******************************************************************************
**                      Includes                                              **
*******************************************************************************/
#include "Platform_Types.h"
/*******************************************************************************
**                      Global Symbols                                        **
*******************************************************************************/

/*******************************************************************************
**                      Global Data                                           **
*******************************************************************************/

/*******************************************************************************
**                      Global Functions                                      **
*******************************************************************************/
#ifdef LeftAir
extern void Rte_Com_Lin_HcmlZcud_Lin2Fr01(HcmlZcud_Lin2Fr01_Msg_Type msg);
#endif
#ifdef RightAir
extern void Rte_Com_Lin_HcmrZcud_Lin2Fr01(HcmrZcud_Lin2Fr01_Msg_Type msg);
#endif
extern ZcudZcud_Lin2Fr01_Msg_Type Rte_Com_Lin_ZcudZcud_Lin2Fr01(void);
extern ZcudZcud_Lin2Fr02_Msg_Type Rte_Com_Lin_ZcudZcud_Lin2Fr02(void);



#endif
