/*******************************************************************************
** xzq: this part is deigned by munual,not generated by tools, and not autosar**
*******************************************************************************/

/*******************************************************************************
**                      Include                                               **
*******************************************************************************/
#include "Fls.h"
#include "Fee.h"
#include "NvM.h"
#include "Rte_Nvm.h"
/*******************************************************************************
**                      Imported Compiler Switch Check                        **
*******************************************************************************/


/*******************************************************************************
**                       Version  Check                                       **
*******************************************************************************/


/*******************************************************************************
**                      Private Variable Definitions                          **
*******************************************************************************/


/*******************************************************************************
**                      Private Type Definitions                              **
*******************************************************************************/
#define StartSig 			(uint64_t)0x5374617274536967U
#define AppStartAddress 	(uint32_t)0x38000U
#define EndSig				(uint64_t)0x456e645369676e61U
/*******************************************************************************
**                      Private Function Declarations                         **
*******************************************************************************/



/*******************************************************************************
**                      Global Variable Definitions                           **
*******************************************************************************/
/* StartCompleteCompatibleSignature */ 
__attribute__((section(".c2c_start_sig"), used)) \
const uint64_t StartCompleteCompatibleSignature = StartSig;

/* ApplicationStartAddress*/ 
__attribute__((section(".c2c_app_start"), used)) \
const uint32_t ApplicationStartAddress = AppStartAddress;  


__attribute__((section(".c2c_func_code"), used)) \
uint32_t CompleteCompatibleFunction(void) {
	uint32 retval = 0;
	retval |= (Nvm_CheckConsistency() << 1);
	retval |= (Nvm_CheckDependence() << 0);
	return retval;
}

/* FunctionAddress */ 
__attribute__((section(".c2c_func_addr"), used)) \
const uint32_t CompleteCompatibleFunctionAddress = (uint32_t)&CompleteCompatibleFunction;


/* EndCompleteCompatibleSignature */
__attribute__((section(".c2c_end_sig"), used)) \
const uint64_t EndCompleteCompatibleSignature = EndSig;

/* EndSignatureAddress 4butes */ 
__attribute__((section(".c2c_end_addr"), used)) \
const uint32_t EndCompleteCompatibleSignatureAddress = (uint32_t)&EndCompleteCompatibleSignature;

/*******************************************************************************
**                      Global Function Definitions                           **
*******************************************************************************/
/* Test code main function to test NVM function */
uint8 Test_Nvm_Cmd;
void TestCode_NvmFunction(void)
{
	uint8 index;
	for(index=0;index<100;index++)
	{
		NvMBlockRamBuffer3[index] = index;
	}
	if(Test_Nvm_Cmd == 0xaa)
	{
		Test_Nvm_Cmd = 0x0;
		NvM_WriteBlock(NvMBlock_All_EventEntry,NvMBlockRamBuffer3);
	}
}
/* Read all block with readall attribute */
uint8 NvM_ReadAll_Immediately(void)
{
	NvM_ReadAll();
	NvM_RequestResultType RequestResultPtr = NVM_REQ_NOT_OK;
	uint16 NVM_OP_USE_TIME = 0u;
	SuspendAllInterrupts();
	do
	{
		NVM_OP_USE_TIME++;
		NvM_MainFunction();
		Fee_MainFunction();
		Fls_MainFunction();
		NvM_GetErrorStatus(0, &RequestResultPtr);
		if (NVM_OP_USE_TIME == 500)
			break;
	} while (RequestResultPtr == NVM_REQ_PENDING);
	ResumeAllInterrupts();
	if (NVM_OP_USE_TIME == 500u)
	{
		return E_NOT_OK;
	}
	else
	{
		return E_OK;
	}
}
/*******************************************************************************
**                      Private Function Definitions                          **
*******************************************************************************/

uint8 Nvm_CheckDependence(void)
{
    uint8 retVal = 1;
    /*
     *0x4BFF0 - 0x4BFF3 ParaMgr_TemV_H_B address
     *0x4BFF4 - 0x4BFF7 ParaMgr_TemV_L_B address
    */
    uint8 *TemplateVersionAddress_H=(uint8 *)0x4FFF0;
    uint8 *TemplateVersionAddress_L=(uint8 *)0x4FFF4;

    uint8 *TemplateVersion_Address_Comple_Value;
    uint8 *TemplateVersion_Address_Store_Value;


    TemplateVersion_Address_Store_Value = ((((uint32)TemplateVersionAddress_H[0])<<24) & 0xFF000000) + 
                                          ((((uint32)TemplateVersionAddress_H[1])<<16) & 0x00FF0000) +
                                          ((((uint32)TemplateVersionAddress_H[2])<<8) & 0x0000FF00)  +
                                           TemplateVersionAddress_H[3];
    
    /*Out of Plash Address*/
    if(TemplateVersion_Address_Store_Value > 0x0007FFFF)
    {
		return retVal;
	}
    
    /*ParaMgr_TemV_H_B compare value*/
    TemplateVersion_Address_Comple_Value = (uint8 *)0x4FFF8;

    if((*TemplateVersion_Address_Comple_Value) != (*TemplateVersion_Address_Store_Value))
    {
		return retVal;
	}
    
    
    TemplateVersion_Address_Store_Value = ((((uint32)TemplateVersionAddress_L[0])<<24) & 0xFF000000) + 
                                          ((((uint32)TemplateVersionAddress_L[1])<<16) & 0x00FF0000) +
                                          ((((uint32)TemplateVersionAddress_L[2])<<8) & 0x0000FF00)  +
                                          TemplateVersionAddress_L[3];
                                          
    /*Out of Plash Address*/
    if(TemplateVersion_Address_Store_Value > 0x0007FFFF)   
    {
		return retVal;
	}

    /*ParaMgr_TemV_L_B compare value*/
    TemplateVersion_Address_Comple_Value = (uint8 *)0x4FFF9;

    if((*TemplateVersion_Address_Comple_Value) != (*TemplateVersion_Address_Store_Value))
    {
		return retVal;
	}

	retVal = 0;
	return retVal;
}




uint8 Nvm_CheckConsistency(void)
{
	uint8 DependenciesValid = *(volatile uint8*)0x0101A03C;
	uint8 ExePart = *(volatile uint8 *)0x0101A003;
	uint8 DataPart = *(volatile uint8 *)0x0101A009;
	uint8 ExeIntegrityValid = *(volatile uint8 *)0x0101A000;
	uint8 DataIntegrityValid = *(volatile uint8 *)0x0101A006;
	volatile uint8 *addr;
	uint8 reval = TRUE;/*can jump to app*/

	for ( addr = (volatile uint8 *)0x0101A000; \
			addr <= (volatile uint8*)0x0101A03C; addr++) 
	{
		if (*addr != 0xFF) 
		{
			reval = FALSE;  /*reset jump flag to false*/ 
			break;
   		}
	}
	
	if(DependenciesValid == 0x01)
	{
		if(ExePart == 0x03U)
		{
			if(ExeIntegrityValid == FALSE)
			{
				reval |=  (1<<2);
			}
			else
			{

			}
		}


		if(DataPart == 0x06U)
		{
			if(DataIntegrityValid == FALSE)
			{
				reval = (1<<3);
			}
			else
			{
				reval = TRUE;
			}
		}

	}

	return reval;
}
/*=======[E N D   O F   F I L E]==============================================*/
