
/*******************************************************************************
** xzq: this part is deigned by munual,not generated by tools, and not autosar **
*******************************************************************************/

/*******************************************************************************
**                      Includes                                              **
*******************************************************************************/
#include "Com.h"
/*******************************************************************************
**                      Private Variable Definitions                          **
*******************************************************************************/


/*******************************************************************************
**                      Global Variable Definitions                           **
*******************************************************************************/


/*******************************************************************************
**                      Private Function Declarations                         **
*******************************************************************************/


/*******************************************************************************
**                      Global Function Definitions                           **
*******************************************************************************/
/* Lin slave header operation process */
uint8 Com_SlaveHeaderIndication(    NetworkHandleType ch,
    P2VAR(Lin_PduType, AUTOMATIC, LINIF_APPL_DATA) PduPtr)
{
	uint8 ret = E_OK;
	uint8 index;

	if(PduPtr->Pid == 0x03)
	{
		for(index=0;index<8;index++)
		{
			PduPtr->SduPtr[index] = index;
		}
	}

	return ret;
}
/* Lin slave reception operation process */
uint8 Com_SlaveRxIndication(NetworkHandleType ch,
    P2VAR(uint8, AUTOMATIC, LINIF_APPL_DATA) Lin_SduPtr)
{
	uint8 ret = E_OK;
		
	return ret;
}
/* Lin slave transmission operation process */
uint8 Com_SlaveTxIndication(NetworkHandleType ch)
{
	uint8 ret = E_OK;
		
	return ret;
}

