#ifndef COM_H
#define COM_H
/*******************************************************************************
** xzq: this part is deigned by munual,not generated by tools, and not autosar **
*******************************************************************************/

/*******************************************************************************
**                      Includes                                              **
*******************************************************************************/
#include "ComStack_Types.h"
#include "Lin.h"
#include "Com_Cfg.h"
#include "Rte_Com.h"
/*******************************************************************************
**                      Global Symbols                                        **
*******************************************************************************/

/*******************************************************************************
**                      Global Data                                           **
*******************************************************************************/

/*******************************************************************************
**                      Global Functions                                      **
*******************************************************************************/
extern uint8 Com_SlaveHeaderIndication(    NetworkHandleType ch,P2VAR(Lin_PduType, AUTOMATIC, LINIF_APPL_DATA) PduPtr);
extern uint8 Com_SlaveRxIndication(NetworkHandleType ch,P2CONST(LinIf_FrameType, AUTOMATIC, LINIF_APPL_CONST) framePtr,P2VAR(uint8, AUTOMATIC, LINIF_APPL_DATA) Lin_SduPtr);
extern uint8 Com_SlaveTxIndication(NetworkHandleType ch);
extern uint8 Com_SetErrorSignal(NetworkHandleType ch,const void *SignalDataPtr);
#endif
