
/*******************************************************************************
** xzq: this part is deigned by munual,not generated by tools, and not autosar **
*******************************************************************************/

/*******************************************************************************
**                      Includes                                              **
*******************************************************************************/
#include "Com.h"
//#include "Rte_E2EXf.h"
#include "Rte_E2E_Callout.h"
/*******************************************************************************
**                      Private Variable Definitions                          **
*******************************************************************************/


/*******************************************************************************
**                      Global Variable Definitions                           **
*******************************************************************************/


/*******************************************************************************
**                      Private Function Declarations                         **
*******************************************************************************/


/*******************************************************************************
**                      Global Variable Declarations                         **
*******************************************************************************/
extern CONST(LinIf_FrameType, LINIF_CONST) LinIf_FrameData[];

/*******************************************************************************
**                      Global Function Definitions                           **
*******************************************************************************/
/* Lin slave header operation process */
uint8 Com_SlaveHeaderIndication(    NetworkHandleType ch,
    P2VAR(Lin_PduType, AUTOMATIC, LINIF_APPL_DATA) PduPtr)
{
	uint8 ret = E_OK;
	uint8 index;

	/* HcmZcud_Lin2Fr01/HcmrZcud_Lin2Fr01 transmission */
	if(PduPtr->Pid == LinIf_FrameData[0].LinIfFrameId)
	{
		for(index=0;index<PduPtr->Dl;index++)
		{
			PduPtr->SduPtr[index] = LinIf_FrameData[0].Buffer[index];
		}
	}
	return ret;
}
/* Lin slave reception operation process */
uint8 Com_SlaveRxIndication(NetworkHandleType ch,
    P2CONST(LinIf_FrameType, AUTOMATIC, LINIF_APPL_CONST) framePtr,
	P2VAR(uint8, AUTOMATIC, LINIF_APPL_DATA) Lin_SduPtr)
{
	uint8 ret = E_OK;
	uint8 index;



	/* ZcudZcud_Lin2Fr01 recption */
	if(framePtr->LinIfFrameId == LinIf_FrameData[1].LinIfFrameId)
	{
		/* E2E */
		Com_ConfirmationProcess(framePtr->LinIfFrameId,Lin_SduPtr);

		for(index=0;index<framePtr->LinIfLength;index++)
		{
			LinIf_FrameData[1].Buffer[index] = Lin_SduPtr[index];
		}
	}
	else if(framePtr->LinIfFrameId == LinIf_FrameData[2].LinIfFrameId)
	{/* ZcudZcud_Lin2Fr02 recption */
		
		/* E2E */
		Com_ConfirmationProcess(framePtr->LinIfFrameId,Lin_SduPtr);

		for(index=0;index<framePtr->LinIfLength;index++)
		{
			LinIf_FrameData[2].Buffer[index] = Lin_SduPtr[index];
		}
	}
	
	return ret;
}
/* Lin slave transmission operation process */
uint8 Com_SlaveTxIndication(NetworkHandleType ch)
{
	uint8 ret = E_OK;
		
	return ret;
}


uint8 Com_SetErrorSignal(NetworkHandleType FrameId,const void *SignalDataPtr)
{
	(void)FrameId;
	TransmErrorFlag = (uint8)(*((const boolean *)SignalDataPtr));
}

uint8 Com_ConfirmationProcess(uint8 frameId,P2VAR(uint8, AUTOMATIC, LINIF_APPL_DATA) Lin_SduPtr)
{
	switch (frameId)
	{
		case 0x03:
			RTE_COM_E2E_ZcudZcud_Lin2Fr01_Handle(Lin_SduPtr);

			break;
		case 0xC4:
			RTE_COM_E2E_ZcudZcud_Lin2Fr02_Handle(Lin_SduPtr);
			
			break;
		default:
			break;
	}
}


void Com_Signal_TimeCounter_10ms(void)
{/*use for signal timeout*/
	Com_Signal_ActnOfLedLoBeam_TimeCount++;
	Com_Signal_ActvnOfIndcr_TimeCount++;
	if(Com_Signal_ActvnOfIndcr_TimeCount>50)
	{
		gs_E2EStateForFailSafe.E2EErrorFlagForFailSafe.bits.ActvnOfIndcrTimeout=1;
	}
	if(Com_Signal_ActnOfLedLoBeam_TimeCount>50)
	{
		gs_E2EStateForFailSafe.E2EErrorFlagForFailSafe.bits.ActnOfLedLoBeamTimeout=1;
	}
}

void Com_Signal_TimeCounter_Reset(uint8 signalIndex)
{
	if(signalIndex = Com_Signal_ActnOfLedLoBeam)
	{
		Com_Signal_ActnOfLedLoBeam_TimeCount = 0;
	}
	else
	{
		Com_Signal_ActvnOfIndcr_TimeCount = 0;
	}
}

