/*******************************************************************************
** xzq: this part is deigned by munual,not generated by tools, and not autosar **
*******************************************************************************/

/*******************************************************************************
**                      Includes                                              **
*******************************************************************************/
#include "Com_Cfg.h"
#include <string.h>
/*******************************************************************************
**                      Private Variable Definitions                          **
*******************************************************************************/

/*******************************************************************************
**                      Global Variable Definitions                           **
*******************************************************************************/
uint8 TransmErrorFlag = 0;
HcmZcud_Lin2Fr01_Msg_Type HcmZcud_Lin2Fr01;
ZcudZcud_Lin2Fr01_Msg_Type ZcudZcud_Lin2Fr01;
ZcudZcud_Lin2Fr02_Msg_Type ZcudZcud_Lin2Fr02;
/*******************************************************************************
**                      Private Function Declarations                         **
*******************************************************************************/


/*******************************************************************************
**                      Global Function Definitions                           **
*******************************************************************************/
void Com_Dem_GetDTCData(uint32 *dtcdata)
{
    *dtcdata = ((HcmZcud_Lin2Fr01.bytes[2] ) | (HcmZcud_Lin2Fr01.bytes[3] << 8) | \
              (HcmZcud_Lin2Fr01.bytes[4]<< 16 ) | (HcmZcud_Lin2Fr01.bytes[5] << 24));
}

void Com_ClearAllSignals(void)
{
    uint8 zero_buf[7] = {0};
    memcpy(ZcudZcud_Lin2Fr01.bytes,zero_buf, 7);
    memcpy(ZcudZcud_Lin2Fr02.bytes, zero_buf, 7);
}