/*******************************************************************************
** xzq: this part is deigned by munual,not generated by tools, and not autosar **
*******************************************************************************/

/*******************************************************************************
**                      Includes                                              **
*******************************************************************************/
#include "Com.h"
/*******************************************************************************
**                      Private Variable Definitions                          **
*******************************************************************************/


/*******************************************************************************
**                      Global Variable Definitions                           **
*******************************************************************************/


/*******************************************************************************
**                      Private Function Declarations                         **
*******************************************************************************/


/*******************************************************************************
**                      Global Function Definitions                           **

/* Hcm transmits HcmZcud_Lin2Fr01 by lin, need set the detail signals in the pointer 'msg'*/
void Rte_Com_Lin_HcmZcud_Lin2Fr01(HcmZcud_Lin2Fr01_Msg_Type msg)
{
	HcmZcud_Lin2Fr01 = msg;
}


/* Hcm receives message 'ZcudZcud_Lin2Fr01',and report it to the app layer */
ZcudZcud_Lin2Fr01_Msg_Type Rte_Com_Lin_ZcudZcud_Lin2Fr01(void)
{
	return ZcudZcud_Lin2Fr01;
}

/* Hcm receives message 'ZcudZcud_Lin2Fr02',and report it to the app layer */
ZcudZcud_Lin2Fr02_Msg_Type Rte_Com_Lin_ZcudZcud_Lin2Fr02(void)
{
	return ZcudZcud_Lin2Fr02;
}


