#ifndef RTENVM_H
#define RTENVM_H

/*******************************************************************************
** xzq: this part is deigned by munual,not generated by tools, and not autosar**
*******************************************************************************/

/*******************************************************************************
**                      Include                                               **
*******************************************************************************/


/*******************************************************************************
**                      Global Symbols                                        **
*******************************************************************************/
typedef unsigned int 		uint32_t;
typedef unsigned long long 	uint64_t;


/*******************************************************************************
**                      Global Functions                                      **
*******************************************************************************/
extern void TestCode_NvmFunction(void);
extern uint8 NvM_ReadAll_Immediately(void);
extern uint8 Nvm_CheckConsistency(void);
extern uint8 Nvm_CheckDependence(void);
#endif /*RTENVM_H*/
