
/*******************************************************************************
**                                                                            **
** Copyright (C) iSOFT   (2016)                                               **
**                                                                            **
** All rights reserved.                                                       **
**                                                                            **
** This document contains proprietary information belonging to iSOFT.         **
** Passing on and copying of this document, and communication                 **
** of its contents is not permitted without prior written authorization.      **
**                                                                            **
********************************************************************************
**                                                                            **
**  FILENAME    : PduR_Cfg.h                                                  **
**                                                                            **
**  Created on  : 2024/12/16 14:21:11                                         
**  Author      : yutao                                                       **
**  Vendor      :                                                             **
**  DESCRIPTION : cfg parameter declaration of PDUR                           **
**                                                                            **
**  SPECIFICATION(S) :   AUTOSAR classic Platform 4.2.2                       **
**                                                                            **
*******************************************************************************/


#ifndef  PDUR_CFG_H
#define  PDUR_CFG_H

/*******************************************************************************
**                      Revision Control History                              **
*******************************************************************************/

/*******************************************************************************
**                      Version Information                                   **
*******************************************************************************/
#define PDUR_CFG_H_AR_MAJOR_VERSION  4U
#define PDUR_CFG_H_AR_MINOR_VERSION  2U
#define PDUR_CFG_H_AR_PATCH_VERSION  2U
#define PDUR_CFG_H_SW_MAJOR_VERSION  1U
#define PDUR_CFG_H_SW_MINOR_VERSION  0U
#define PDUR_CFG_H_SW_PATCH_VERSION  0U
/*******************************************************************************
**                      Include Section                                       **
*******************************************************************************/

/*******************************************************************************
**                      Macros                                                **
*******************************************************************************/

/* Zero cost operation only support */
#define PDUR_ZERO_COST_OPERATION        STD_OFF

/* Config Use DET or Not, Generated by Tool */
#define PDUR_DEV_ERROR_DETECT           STD_OFF

/* Enable support for MetaData handling in CAN-CAN-routing */
#define PDUR_META_DATA_SUPPORT          STD_OFF

/* If true the PduR_GetVersionInfo API is available */
#define PDUR_VERSION_INFO_API           STD_OFF

#define PDUR_BSW_MODULE_SUM             3U
#define PDUR_COM      0U
#define PDUR_LINIF      1U
#define PDUR_DCM      2U

#define PDUR_CANIF_SUPPORT        STD_OFF
#define PDUR_CANTP_SUPPORT        STD_OFF
#define PDUR_J1939TP_SUPPORT      STD_OFF
#define PDUR_COM_SUPPORT          STD_ON
#define PDUR_DCM_SUPPORT          STD_ON
#define PDUR_J1939DCM_SUPPORT     STD_OFF
#define PDUR_IPDUM_SUPPORT        STD_OFF
#define PDUR_J1939RM_SUPPORT      STD_OFF
#define PDUR_LDCOM_SUPPORT        STD_OFF
#define PDUR_SECOC_SUPPORT        STD_OFF
#define PDUR_DBG_SUPPORT          STD_OFF
#define PDUR_CANNM_SUPPORT        STD_OFF
#define PDUR_OSEKNM_SUPPORT       STD_OFF
#define PDUR_LINIF_SUPPORT        STD_ON
#define PDUR_LINTP_SUPPORT        STD_OFF
#define PDUR_FRIF_SUPPORT         STD_OFF
#define PDUR_FRNM_SUPPORT         STD_OFF
#define PDUR_DOIP_SUPPORT         STD_OFF
#define PDUR_SOAD_SUPPORT         STD_OFF
#define PDUR_UDPNM_SUPPORT        STD_OFF
#define PDUR_DLT_SUPPORT          STD_OFF

#define PDUR_TP_SUPPORT           STD_OFF
#define PDUR_UPMODE_SUPPORT       STD_ON

#define PDUR_COM_CANCEL_TRANSMIT           STD_OFF
#define PDUR_DCM_CANCEL_TRANSMIT           STD_OFF
#define PDUR_J1939DCM_CANCEL_TRANSMIT      STD_OFF
#define PDUR_J1939RM_CANCEL_TRANSMIT       STD_OFF
#define PDUR_LDCOM_CANCEL_TRANSMIT         STD_OFF
#define PDUR_SECOC_CANCEL_TRANSMIT         STD_OFF
#define PDUR_UPMODE_CANCEL_TRANSMIT        STD_OFF

#define PDUR_COM_CHANGE_PARAMETER          STD_OFF
#define PDUR_DCM_CHANGE_PARAMETER          STD_OFF
#define PDUR_J1939DCM_CHANGE_PARAMETER     STD_OFF
#define PDUR_LDCOM_CHANGE_PARAMETER        STD_OFF
#define PDUR_UPMODE_CHANGE_PARAMETER       STD_OFF

#define PDUR_COM_CANCEL_RECEIVE            STD_OFF
#define PDUR_DCM_CANCEL_RECEIVE            STD_OFF
#define PDUR_J1939DCM_CANCEL_RECEIVE       STD_OFF
#define PDUR_LDCOM_CANCEL_RECEIVE          STD_OFF
#define PDUR_UPMODE_CANCEL_RECEIVE         STD_OFF

#define PDUR_DOIP_TX_CONFIRMATION         STD_OFF

#define PDUR_SOAD_TX_CONFIRMATION         STD_OFF
#define PDUR_SOAD_TRIGGER_TRANSMIT        STD_OFF

#define PDUR_UDPNM_TX_CONFIRMATION         STD_OFF
#define PDUR_UDPNM_TRIGGER_TRANSMIT        STD_OFF

#define PDUR_CANIF_TX_CONFIRMATION         STD_OFF
#define PDUR_CANIF_TRIGGER_TRANSMIT        STD_OFF

#define PDUR_LINIF_TX_CONFIRMATION         STD_ON
#define PDUR_LINIF_TRIGGER_TRANSMIT        STD_ON

#define PDUR_CANNM_TX_CONFIRMATION         STD_OFF
#define PDUR_CANNM_TRIGGER_TRANSMIT        STD_OFF

#define PDUR_OSEKNM_TX_CONFIRMATION         STD_OFF
#define PDUR_OSEKNM_TRIGGER_TRANSMIT        STD_OFF

#define PDUR_SECOC_TX_CONFIRMATION         STD_OFF

#define PDUR_IPDUM_TX_CONFIRMATION         STD_OFF
#define PDUR_IPDUM_TRIGGER_TRANSMIT        STD_OFF

#define PDUR_SRC_PDU_SUM           6U
#define PDUR_SRCPDU_HCML_MasterReq          0U
#define PDUR_SRCPDU_Hcml_MasterReq_Fun          1U
#define PDUR_SRCPDU_Dcm_HCML_SlaveResp          2U
#define PDUR_SRCPDU_Com_HcmlZcud_Lin2Fr01          3U
#define PDUR_SRCPDU_ZcudZcud_Lin2Fr01          4U
#define PDUR_SRCPDU_ZcudZcud_Lin2Fr02          5U


#define PDUR_DEST_PDU_SUM              6U
#define PDUR_DEST_GATEWAY_TP_PDU_SUM   0U/*all gateway dest tp pdu*/
#define PDUR_DESTPDU_Dcm_HCML_MasterReq          0U
#define PDUR_DESTPDU_Dcm_Hcml_MasterReq_Fun          1U
#define PDUR_DESTPDU_HCML_SlaveResp          2U
#define PDUR_DESTPDU_HcmlZcud_Lin2Fr01          3U
#define PDUR_DESTPDU_Com_ZcudZcud_Lin2Fr01          4U
#define PDUR_DESTPDU_Com_ZcudZcud_Lin2Fr02          5U

#define PDUR_ROUTING_PATH_GROUP_SUM        0U


#define PDUR_SRC_UP_MULTICAST_TX_IF_SUM              0U/*up local mode(COM/DCM),for 1:n(n>1) if transmit*/
#define PDUR_SRC_UP_MULTICAST_TX_TP_SUM              0U /*up local mode(COM/DCM),for 1:n(n>1) tp transmit*/
#define PDUR_GATEWAY_DIRECT_BUFFER_PDU_SUM           0U/*used for gateway direct pdu which have configed buffer*/


#define PDUR_TP_BUFFER_SUM           0U
#define PDUR_TX_BUFFER_SUM           0U /*just route dest pdu have the txbuffer*/



#define PDUR_DEFAULT_VALUE_LENGTH           0U/*all dest pdu(PDUR_TRIGGERTRANSMIT) default value length*/
#define PDUR_DEFAULT_VALUE                  0U /*use default value pdu number*/

#endif  /* end of PDUR_CFG_H */

/*******************************************************************************
**                      End of file                                           **
*******************************************************************************/


