#ifndef Z20K14XMC_STL_NVIC_CONFIG_H
#define Z20K14XMC_STL_NVIC_CONFIG_H

/* Number of maximum tests that the user wants to run */
#define STL_NUM_MAX_TESTS        41820
/* Number of necessary tests to fulfill phases from 0 to 3 completely, depending on hardware configuration (interrupt number) */
#define STL_TEST_MAX_STEPS       41820
/* Number of tests to fulfill pending tree phase 0 completely, depending on hardware configuration (interrupt number) */
#define STL_PHASE_0_LAST         20705
/* Number of tests to fulfill pending tree phase 1 completely, depending on hardware configuration (interrupt number) */
#define STL_PHASE_1_LAST         20910
/* Number of tests to fulfill active tree phase 2 completely, depending on hardware configuration (interrupt number) */
#define STL_PHASE_2_LAST         41616
/* IRQ maximum index value, depending on hardware configuration (starting from 0) */
#define STL_IRQMAX               204

#define STL_NEXT_IRQ_IDX_AFTER_IRQ_0    1
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_1    2
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_2    3
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_3    4
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_4    5
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_5    6
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_6    7
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_7    8
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_8    9
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_9    10
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_10    11
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_11    12
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_12    13
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_13    14
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_14    15
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_15    16
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_16    17
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_17    18
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_18    19
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_19    20
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_20    21
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_21    22
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_22    23
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_23    24
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_24    25
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_25    26
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_26    27
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_27    28
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_28    29
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_29    31
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_30    31
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_31    32
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_32    33
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_33    34
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_34    35
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_35    37
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_36    37
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_37    38
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_38    39
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_39    40
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_40    41
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_41    43
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_42    43
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_43    44
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_44    45
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_45    46
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_46    47
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_47    49
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_48    49
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_49    50
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_50    51
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_51    52
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_52    53
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_53    54
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_54    55
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_55    56
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_56    57
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_57    58
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_58    59
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_59    60
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_60    61
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_61    62
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_62    63
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_63    64
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_64    65
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_65    66
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_66    67
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_67    68
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_68    69
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_69    70
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_70    71
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_71    72
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_72    73
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_73    74
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_74    75
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_75    76
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_76    77
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_77    78
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_78    79
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_79    80
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_80    81
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_81    82
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_82    83
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_83    84
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_84    85
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_85    86
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_86    87
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_87    88
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_88    89
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_89    90
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_90    91
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_91    92
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_92    93
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_93    94
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_94    95
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_95    96
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_96    97
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_97    98
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_98    99
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_99    100
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_100    101
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_101    102
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_102    103
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_103    104
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_104    105
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_105    106
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_106    107
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_107    108
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_108    109
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_109    110
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_110    111
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_111    112
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_112    113
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_113    114
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_114    115
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_115    116
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_116    117
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_117    118
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_118    119
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_119    120
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_120    121
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_121    122
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_122    123
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_123    124
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_124    125
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_125    126
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_126    127
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_127    128
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_128    129
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_129    130
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_130    131
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_131    132
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_132    133
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_133    134
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_134    135
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_135    136
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_136    137
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_137    138
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_138    139
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_139    140
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_140    141
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_141    142
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_142    143
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_143    144
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_144    145
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_145    146
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_146    147
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_147    148
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_148    149
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_149    150
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_150    154
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_151    154
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_152    154
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_153    154
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_154    155
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_155    156
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_156    157
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_157    158
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_158    159
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_159    160
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_160    161
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_161    162
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_162    163
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_163    164
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_164    165
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_165    166
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_166    167
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_167    168
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_168    169
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_169    170
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_170    171
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_171    172
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_172    173
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_173    174
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_174    175
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_175    176
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_176    177
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_177    178
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_178    179
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_179    180
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_180    181
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_181    182
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_182    183
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_183    184
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_184    185
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_185    186
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_186    187
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_187    188
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_188    189
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_189    190
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_190    191
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_191    192
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_192    193
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_193    194
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_194    195
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_195    196
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_196    197
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_197    198
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_198    199
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_199    200
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_200    201
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_201    202
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_202    203
#define STL_NEXT_IRQ_IDX_AFTER_IRQ_203    204

static const uint32_t m4_stl_next_irq_index[204] = {
    STL_NEXT_IRQ_IDX_AFTER_IRQ_0,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_1,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_2,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_3,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_4,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_5,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_6,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_7,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_8,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_9,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_10,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_11,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_12,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_13,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_14,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_15,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_16,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_17,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_18,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_19,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_20,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_21,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_22,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_23,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_24,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_25,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_26,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_27,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_28,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_29,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_30,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_31,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_32,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_33,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_34,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_35,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_36,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_37,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_38,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_39,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_40,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_41,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_42,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_43,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_44,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_45,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_46,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_47,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_48,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_49,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_50,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_51,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_52,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_53,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_54,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_55,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_56,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_57,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_58,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_59,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_60,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_61,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_62,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_63,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_64,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_65,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_66,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_67,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_68,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_69,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_70,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_71,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_72,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_73,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_74,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_75,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_76,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_77,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_78,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_79,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_80,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_81,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_82,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_83,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_84,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_85,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_86,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_87,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_88,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_89,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_90,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_91,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_92,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_93,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_94,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_95,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_96,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_97,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_98,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_99,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_100,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_101,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_102,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_103,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_104,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_105,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_106,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_107,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_108,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_109,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_110,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_111,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_112,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_113,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_114,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_115,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_116,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_117,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_118,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_119,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_120,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_121,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_122,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_123,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_124,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_125,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_126,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_127,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_128,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_129,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_130,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_131,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_132,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_133,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_134,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_135,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_136,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_137,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_138,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_139,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_140,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_141,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_142,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_143,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_144,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_145,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_146,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_147,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_148,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_149,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_150,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_151,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_152,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_153,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_154,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_155,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_156,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_157,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_158,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_159,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_160,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_161,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_162,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_163,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_164,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_165,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_166,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_167,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_168,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_169,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_170,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_171,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_172,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_173,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_174,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_175,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_176,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_177,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_178,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_179,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_180,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_181,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_182,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_183,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_184,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_185,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_186,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_187,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_188,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_189,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_190,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_191,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_192,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_193,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_194,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_195,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_196,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_197,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_198,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_199,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_200,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_201,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_202,
    STL_NEXT_IRQ_IDX_AFTER_IRQ_203
};

static const uint32_t m4_stl_test_param[5] = {
    STL_TEST_MAX_STEPS, STL_PHASE_0_LAST, STL_PHASE_1_LAST, STL_PHASE_2_LAST, STL_IRQMAX};

#endif
