/*******************************************************************************
**                                                                            **
** Copyright (C) iSOFT   (2022)                                               **
**                                                                            **
** All rights reserved.                                                       **
**                                                                            **
** This document contains proprietary information belonging to iSOFT.         **
** Passing on and copying of this document, and communication                 **
** of its contents is not permitted without prior written authorization.      **
**                                                                            **
********************************************************************************
**                                                                            **
**  FILENAME    : Rte_Cbk.h                                                   **
**                                                                            **
**  Created on  :2024/07/12 10:38:54                                                             
**  Author      : ISOFT                                                       **
**  Vendor      :                                                             **
**  DESCRIPTION : If there is no RTE module, it is generated by COM           **
**                                                                            **
**  SPECIFICATION(S) :   AUTOSAR classic Platform 4.2.2                       **
**                                                                            **
*******************************************************************************/

#ifndef  RTE_CBK_H
#define  RTE_CBK_H

#include "ComStack_Types.h"
typedef union{
    struct{
       uint32 ActnOfLedLoBeamTimeout :1;
       uint32 ActnOfLedLoBeamCntErr  :1;
       uint32 ActnOfLedLoBeamCrcErr  :1;
       uint32 UsgModeTimeout         :1;
       uint32 UsgModeCntErr          :1;
       uint32 UsgModeCrcErr          :1;
       uint32 VehSpdTimeout          :1;
       uint32 VehSpdCntErr           :1;
       uint32 VehSpdCrcErr           :1;
       uint32 ActvnOfIndcrTimeout    :1;
       uint32 ActvnOfIndcrCntErr     :1;
       uint32 ActvnOfIndcrCrcErr     :1;
       uint32 SteerWhlSnsrTimeout    :1;
       uint32 SteerWhlSnsrCntErr     :1;
       uint32 SteerWhlSnsrCrcErr     :1;
       uint32 LvlgSwtSetReqTimeout   :1;
       uint32 LvlgSwtSetReqCrcErr    :1;
    }bits;
    uint32 E2EErrFlag;
}U_E2EErrorFlag;

typedef struct{
    U_E2EErrorFlag E2EErrorFlagForFailSafe;
    uint8 ActnOfLedLoBeamCrcErrResumeCnt;
    uint8 ActnOfLedLoBeamCounterErrResumeCnt;
    uint8 UsgModeCrcErrResumeCnt;
    uint8 UsgModeCounterErrResumeCnt;
    uint8 VehSpdCrcErrResumeCnt;
    uint8 VehSpdCounterErrResumeCnt;
    uint8 ActvnOfIndcrCrcErrResumeCnt;
    uint8 ActvnOfIndcrCounterErrResumeCnt;
    uint8 SteerWhlSnsrCrcErrResumeCnt;
    uint8 SteerWhlSnsrCounterErrResumeCnt;
    uint8 LvlgSwtSetReqCrcErrResumeCnt;
}S_E2EStateForFailSafe;

extern S_E2EStateForFailSafe gs_E2EStateForFailSafe;

void Rte_COMCbkTAck_StsOfLedHiBeamLe_IPDU_COM_HcmlBodyExpoSignalIPDU02(void);

void Rte_COMCbkTErr_StsOfLedHiBeamLe_IPDU_COM_HcmlBodyExpoSignalIPDU02(void);

void Rte_COMCbkTAck_StsOfLedLoBeamLe_IPDU_COM_HcmlBodyExpoSignalIPDU02(void);

void Rte_COMCbkTErr_StsOfLedLoBeamLe_IPDU_COM_HcmlBodyExpoSignalIPDU02(void);

void Rte_COMCbkTAck_ExtrLiShowStoreStsFrntLe_IPDU_COM_HcmlBodyExpoSignalIPDU02(void);

void Rte_COMCbkTErr_ExtrLiShowStoreStsFrntLe_IPDU_COM_HcmlBodyExpoSignalIPDU02(void);

void Rte_COMCbkTAck_StsOfLedLeLogoLamp_IPDU_COM_HcmlBodyExpoSignalIPDU02(void);

void Rte_COMCbkTErr_StsOfLedLeLogoLamp_IPDU_COM_HcmlBodyExpoSignalIPDU02(void);

void Rte_COMCbkTAck_StsOfLedFrntTurnIndcrLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_StsOfLedFrntTurnIndcrLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_StsOfTouristModLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_StsOfTouristModLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_StsOfLedDaytiRunngLampLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_StsOfLedDaytiRunngLampLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_StsOfLedFrntFogLampLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_StsOfLedFrntFogLampLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_StsOfAfsLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_StsOfAfsLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_StsOfAhbcLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_StsOfAhbcLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_StsOfSwvlgLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_StsOfSwvlgLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_StsOfFrntSideMkrLampLe2_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_StsOfFrntSideMkrLampLe2_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_StsOfLedCornrgLampLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_StsOfLedCornrgLampLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_StsOfLedFrntPosnLampLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_StsOfLedFrntPosnLampLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_HdlampLeInpSts1_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_HdlampLeInpSts1_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_HdlampLeInpSts2_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_HdlampLeInpSts2_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_ExtrLiShowActvnFrntLeFb_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_ExtrLiShowActvnFrntLeFb_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_DwnLoadStsFbOfHdlampLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_DwnLoadStsFbOfHdlampLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_ExtrLiShowActvnLeLogoFb_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_ExtrLiShowActvnLeLogoFb_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_DwnLoadStsFbOfLogoLampLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_DwnLoadStsFbOfLogoLampLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTAck_StsOfWelGbyFrntLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbkTErr_StsOfWelGbyFrntLe_IPDU_COM_HcmlBodyExpoSignalIPDU04(void);

void Rte_COMCbk_LiOprnMod_IPDU_COM_CemBodyExpoCommonSignalIPdu01(void);

void Rte_COMCbk_AutWinWipgCmd_IPDU_COM_CemBodyExpoCommonSignalIPdu01(void);

void Rte_COMCbk_YawRateReqdByDrvr_IPDU_COM_CemBodyExpoCommonSignalIPdu02(void);

void Rte_COMCbk_ExtrLiRlyPwrDwn_IPDU_COM_CemBodyExpoCommonSignalIPDU06(void);

void Rte_COMCbk_BkpOfDstTrvld_IPDU_COM_CemBodyExpoCommonSignalIPDU06(void);

void Rte_COMCbk_Body2CntrForMissCom_IPDU_COM_CemBodyExpoCommonSignalIPDU07(void);

void Rte_COMCbk_ActnOfLedFrntCrossLamp_IPDU_COM_CemBodyExpoCommonSignalIPDU07(void);

void Rte_COMCbk_ActnOfLedGrilleLamp_IPDU_COM_CemBodyExpoCommonSignalIPDU07(void);

void Rte_COMCbk_ActnOfLedRiLogoLamp_IPDU_COM_CemBodyExpoCommonSignalIPDU07(void);

void Rte_COMCbk_CarTiGlb_IPDU_COM_CemBodyExpoCommonSignalIPDU07(void);

void Rte_COMCbk_TooManyCars_IPDU_COM_CemBodyExpoCommonSignalIPDU08(void);

void Rte_COMCbk_WipgAutFrntMod_IPDU_COM_CemBodyExpoCommonSignalIPdu21(void);

void Rte_COMCbk_RainLi_IPDU_COM_CemBodyExpoCommonSignalIPdu21(void);

void Rte_COMCbk_CameraStsforAHBC_IPDU_COM_CemBodyExpoCommonSignalIPdu21(void);

void Rte_COMCbk_ExtrLiShowFileTxReq_IPDU_COM_CemBodyExpoSignalIPdu01(void);

void Rte_COMCbk_ExtrLiShowActvnReq_IPDU_COM_CemBodyExpoSignalIPdu01(void);

void Rte_COMCbk_ActnOfLedPosnLampDyn_IPDU_COM_CemBodyExpoSignalIPdu42(void);

void Rte_COMCbk_ActnOfLedFrntCrossLampDyn_IPDU_COM_CemBodyExpoSignalIPdu42(void);

void Rte_COMCbk_ActnOfLedGrilleLampDyn_IPDU_COM_CemBodyExpoSignalIPdu42(void);

void Rte_COMCbk_ActnOfLedRiLogoLampDyn_IPDU_COM_CemBodyExpoSignalIPdu42(void);

void Rte_COMCbk_ActvnOfHomeSafe_IPDU_COM_CemBodyExpoSignalIPdu42(void);

void Rte_COMCbk_LitArea_IPDU_COM_CemBodyExpoSignalIPdu45(void);

void Rte_COMCbk_ActvnOfApproach_IPDU_COM_CemBodyExpoSignalIPdu45(void);

void Rte_COMCbk_ActvnOfCarLoctr_IPDU_COM_CemBodyExpoSignalIPdu45(void);

void Rte_COMCbk_ActvnOfWaitMode_IPDU_COM_CemBodyExpoSignalIPdu45(void);

void Rte_COMCbk_IndcrNoSeq_IPDU_COM_CemBodyExpoSignalIPdu45(void);

void Rte_COMCbk_ActnOfLedCornrgLampRi_IPDU_COM_CemBodyExpoSignalIPdu50(void);

void Rte_COMCbk_ActnOfLedDaytiRunngLamp_IPDU_COM_CemBodyExpoSignalIPdu50(void);

void Rte_COMCbk_ActnOfLedFrntFogLamp_IPDU_COM_CemBodyExpoSignalIPdu50(void);

void Rte_COMCbk_ActnOfLedHiBeam_IPDU_COM_CemBodyExpoSignalIPdu50(void);

void Rte_COMCbk_ActnOfLedPosnLamp_IPDU_COM_CemBodyExpoSignalIPdu50(void);

void Rte_COMCbk_ActvnOfAfs_IPDU_COM_CemBodyExpoSignalIPdu50(void);

void Rte_COMCbk_ActvnOfAhbc_IPDU_COM_CemBodyExpoSignalIPdu50(void);

void Rte_COMCbk_ActvnOfAhl_IPDU_COM_CemBodyExpoSignalIPdu50(void);

void Rte_COMCbk_ActvnOfDbl_IPDU_COM_CemBodyExpoSignalIPdu50(void);

void Rte_COMCbk_ActvnOfGoodByeLi_IPDU_COM_CemBodyExpoSignalIPdu50(void);

void Rte_COMCbk_ActvnOfTouristMod_IPDU_COM_CemBodyExpoSignalIPdu50(void);

void Rte_COMCbk_ActvnOfWelcomeLi_IPDU_COM_CemBodyExpoSignalIPdu50(void);

void Rte_COMCbk_IndcrSts_IPDU_COM_CemBodyExpoSignalIPdu51(void);

void Rte_COMCbk_WelcomeGoodbyeModeReq_IPDU_COM_CemBodyExpoSignalIPdu59(void);

void Rte_COMCbk_WelLiFileTxReq_IPDU_COM_CemBodyExpoSignalIPdu67(void);

void Rte_COMCbk_ActvnOfLiForComity_IPDU_COM_CemBodyExpoSignalIPdu115(void);

void Rte_COMCbk_ActvnOfLiForSpkr_IPDU_COM_CemBodyExpoSignalIPdu115(void);

void Rte_COMCbk_ActvnOfLiForWait_IPDU_COM_CemBodyExpoSignalIPdu115(void);

void Rte_COMCbk_ActvnOfADB_IPDU_COM_CemBodyExpoSignalIPdu115(void);

void Rte_COMCbk_isCanNmEira(void);

void Rte_COMCbk_igVehCfgPrmExt(void);

void Rte_COMCbk_igTrafficSignForADB1(void);

void Rte_COMCbk_igVehObjforADB7(void);

void Rte_COMCbk_igVehObjforADB5(void);

void Rte_COMCbk_igVehCfgPrm(void);

void Rte_COMCbk_igVehModMngtGlbSafe1(void);

void Rte_COMCbkRxTOut_igVehModMngtGlbSafe1(void);

void Rte_COMCbk_igVehObjforADB8(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForLedCornrgLampRi(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForLedFrntPosnLampRi(void);

void Rte_COMCbk_igVehObjforADB3(void);

void Rte_COMCbk_igBrkPedlrRat(void);

void Rte_COMCbk_igVehObjforADB2(void);

void Rte_COMCbk_igVehObjforADB6(void);

void Rte_COMCbk_igAccrPedlRat(void);

void Rte_COMCbk_igBrkPedlSnsr(void);

void Rte_COMCbk_igAmbTRaw(void);

void Rte_COMCbk_igVehBattU(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForLedDaytiRunngLampRi(void);

void Rte_COMCbk_igLvlgSwtSetReq(void);

void Rte_COMCbkRxTOut_igLvlgSwtSetReq(void);

void Rte_COMCbk_igOutdBri(void);

void Rte_COMCbk_igVehObjforADB1(void);

void Rte_COMCbk_igVehObjforADB4(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForLedAllWthrLampRi(void);

void Rte_COMCbk_igDwnLoadDynLitPrmForLedLoBeamRi(void);

void Rte_COMCbk_igSteerWhlSnsr(void);

void Rte_COMCbkRxTOut_igSteerWhlSnsr(void);

void Rte_COMCbk_igDwnLoadDynLitPrmForLedHiBeamRi(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForLedFrntTurnIndcrRi(void);

void Rte_COMCbk_igVehSpdLgt(void);

void Rte_COMCbkRxTOut_igVehSpdLgt(void);

void Rte_COMCbk_igActvnOfIndcr(void);

void Rte_COMCbkRxTOut_igActvnOfIndcr(void);

void Rte_COMCbk_igIndcrPat(void);

void Rte_COMCbk_igTrafficSignForADB2(void);

void Rte_COMCbk_igVehObjforAHB(void);

void Rte_COMCbk_igBrkPedlVal(void);

void Rte_COMCbk_igWipgInfo(void);

void Rte_COMCbk_igActnOfLedLoBeam(void);

void Rte_COMCbkRxTOut_igActnOfLedLoBeam(void);

void Rte_COMCbk_igSuspPosnVertAg(void);

void Rte_COMCbk_igSuspPosnVertLvl(void);

void Rte_COMCbk_igDwnLoadDynLitPrmLedRiGrilleLamp(void);

void Rte_COMCbk_igDwnLoadDynLitPrmLedRiSideLogoLi(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp1(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp2(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp3(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp4(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp5(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp6(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp7(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp8(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp9(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp10(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp11(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp12(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp13(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp14(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp15(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp16(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp17(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp18(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp19(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp20(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp21(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp22(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp23(void);

void Rte_COMCbk_igDwnLoadDynLtgPrmForFrntRiGrp24(void);

void Rte_COMCbk_igTiAndDateIndcn(void);

#endif
