/*
 * ParaMgr.h
 *
 *  Created on: 2024��1��10��
 *      Author: mihuiliang
 */

#ifndef BASE_PARAMETER_PARAMGR_H_
#define BASE_PARAMETER_PARAM_
extern const uint16 ParaMgr_Low_Beam_Flat_W;
extern const uint16 ParaMgr_High_Beam_Sail_W;
extern const uint16 ParaMgr_Daytime_Running_Light_W;
extern const uint16 ParaMgr_Position_Light_W;
extern const uint16 ParaMgr_Turn_Indicator_W;
extern const uint16 ParaMgr_Cornering_Light_W;
extern const uint16 ParaMgr_Fog_Lamp_W;
extern const uint16 ParaMgr_Logo_Lamp_W;
extern const uint16 ParaMgr_Front_Cross_Lamp_W;
extern const uint16 ParaMgr_Grille_Lamp_W;
extern const uint16 ParaMgr_Assistant_Light_W;
extern const uint16 ParaMgr_Side_Marker_Lamp_W;
extern const uint16 ParaMgr_Fan2_W;
extern const uint16 ParaMgr_DCMotor_Supply_W;
extern const uint16 ParaMgr_CH1_LF_MASK_W;
extern const uint16 ParaMgr_CH1Tap_LF_MASK_W;
extern const uint16 ParaMgr_CH2_LF_MASK_W;
extern const uint16 ParaMgr_CH2Alt_LF_MASK_W;
extern const uint16 ParaMgr_CH3_LF_MASK_W;
extern const uint16 ParaMgr_CH4_LF_MASK_W;
extern const uint16 ParaMgr_HSD1_LF_MASK_W;
extern const uint16 ParaMgr_HSD2_LF_MASK_W;
extern const uint16 ParaMgr_LightN_1_W;
extern const uint16 ParaMgr_DRL_TI_surfaces_Near_W;
extern const uint16 ParaMgr_DRL_TI_surfaces_apparent_W;
extern const uint16 ParaMgr_POS_TI_surfaces_apparent_W;
extern const uint8 ParaMgr_pCh1Ena_B;
extern const uint8 ParaMgr_pCh1_TapEna_B;
extern const uint8 ParaMgr_pCh2Ena_B;
extern const uint8 ParaMgr_pCh2_AltEna_B;
extern const uint8 ParaMgr_pCh3Ena_B;
extern const uint8 ParaMgr_pCh4Ena_B;
extern const uint8 ParaMgr_pHSD1Ena_B;
extern const uint8 ParaMgr_pHSD2Ena_B;
extern const uint8 ParaMgr_pHW_OUT1Ena_B;
extern const uint8 ParaMgr_pHW_OUT2Ena_B;
extern const uint16 ParaMgr_pCh1MinVolt_W ;
extern const uint16 ParaMgr_pCh1_TapMinVolt_W ;
extern const uint16 ParaMgr_pCh2MinVolt_W ;
extern const uint16 ParaMgr_pCh2_AltMinVolt_W ;
extern const uint16 ParaMgr_pCh3MinVolt_W ;
extern const uint16 ParaMgr_pCh4MinVolt_W ;
extern const uint16 ParaMgr_pCh1MaxVolt_W ;
extern const uint16 ParaMgr_pCh1_TapMaxVolt_W ;
extern const uint16 ParaMgr_pCh2MaxVolt_W ;
extern const uint16 ParaMgr_pCh2_AltMaxVolt_W ;
extern const uint16 ParaMgr_pCh3MaxVolt_W ;
extern const uint16 ParaMgr_pCh4MaxVolt_W ;
extern const uint16 ParaMgr_pLedNomCurrent_CH1_W ;
extern const uint16 ParaMgr_pLedNomCurrent_Ch1_Tap_W ;
extern const uint16 ParaMgr_pLedNomCurrent_Ch2_W;
extern const uint16 ParaMgr_pLedNomCurrent_Ch2_Alt_W;
extern const uint16 ParaMgr_pLedNomCurrent_Ch3_W ;
extern const uint16 ParaMgr_pLedNomCurrent_Ch4_W ;
extern const uint16 ParaMgr_pLedMinCurrent_CH1_W ;
extern const uint16 ParaMgr_pLedMinCurrent_Ch1_Tap_W ;
extern const uint16 ParaMgr_pLedMinCurrent_Ch2_W ;
extern const uint16 ParaMgr_pLedMinCurrent_Ch2_Alt_W ;
extern const uint16 ParaMgr_pLedMinCurrent_Ch3_W ;
extern const uint16 ParaMgr_pLedMinCurrent_Ch4_W ;
extern const uint16 ParaMgr_pLedMaxCurrent_CH1_W ;
extern const uint16 ParaMgr_pLedMaxCurrent_Ch1_Tap_W ;
extern const uint16 ParaMgr_pLedMaxCurrent_Ch2_W ;
extern const uint16 ParaMgr_pLedMaxCurrent_Ch2_Alt_W ;
extern const uint16 ParaMgr_pLedMaxCurrent_Ch3_W ;
extern const uint16 ParaMgr_pLedMaxCurrent_Ch4_W ;
extern const uint16 ParaMgr_pLedPmaxPower_CH1_W ;
extern const uint16 ParaMgr_pLedPmaxPower_Ch1_Tap_W ;
extern const uint16 ParaMgr_pLedPmaxPower_Ch2_W;
extern const uint16 ParaMgr_pLedPmaxPower_Ch2_Alt_W;
extern const uint16 ParaMgr_pLedPmaxPower_Ch3_W ;
extern const uint16 ParaMgr_pLedPmaxPower_Ch4_W ;
extern const uint8 ParaMgr_pLedDerTemp1_Ch1_B;
extern const uint8 ParaMgr_pLedDerTemp1_Ch1_Tap_B;
extern const uint8 ParaMgr_pLedDerTemp1_Ch2_B;
extern const uint8 ParaMgr_pLedDerTemp1_Ch2_Alt_B;
extern const uint8 ParaMgr_pLedDerTemp1_Ch3_B;
extern const uint8 ParaMgr_pLedDerTemp1_Ch4_B;
extern const uint8 ParaMgr_pLedDerTemp2_Ch1_B ;
extern const uint8 ParaMgr_pLedDerTemp2_Ch1_Tap_B ;
extern const uint8 ParaMgr_pLedDerTemp2_Ch2_B ;
extern const uint8 ParaMgr_pLedDerTemp2_Ch2_Alt_B ;
extern const uint8 ParaMgr_pLedDerTemp2_Ch3_B ;
extern const uint8 ParaMgr_pLedDerTemp2_Ch4_B ;
extern const uint8 ParaMgr_pLedDerTemp3_Ch1_B ;
extern const uint8 ParaMgr_pLedDerTemp3_Ch1_Tap_B ;
extern const uint8 ParaMgr_pLedDerTemp3_Ch2_B ;
extern const uint8 ParaMgr_pLedDerTemp3_Ch2_Alt_B ;
extern const uint8 ParaMgr_pLedDerTemp3_Ch3_B ;
extern const uint8 ParaMgr_pLedDerTemp3_Ch4_B ;
extern const uint8 ParaMgr_pLedDerTemp4_Ch1_B ;
extern const uint8 ParaMgr_pLedDerTemp4_Ch1_Tap_B ;
extern const uint8 ParaMgr_pLedDerTemp4_Ch2_B ;
extern const uint8 ParaMgr_pLedDerTemp4_Ch2_Alt_B ;
extern const uint8 ParaMgr_pLedDerTemp4_Ch3_B ;
extern const uint8 ParaMgr_pLedDerTemp4_Ch4_B ;
extern const uint8 ParaMgr_pLedDerTemp5_Ch1_B ;
extern const uint8 ParaMgr_pLedDerTemp5_Ch1_Tap_B ;
extern const uint8 ParaMgr_pLedDerTemp5_Ch2_B ;
extern const uint8 ParaMgr_pLedDerTemp5_Ch2_Alt_B ;
extern const uint8 ParaMgr_pLedDerTemp5_Ch3_B ;
extern const uint8 ParaMgr_pLedDerTemp5_Ch4_B ;
extern const uint8 ParaMgr_pLedDerPwrA_Ch1_B ;
extern const uint8 ParaMgr_pLedDerPwrA_Ch1_Tap_B ;
extern const uint8 ParaMgr_pLedDerPwrA_Ch2_B ;
extern const uint8 ParaMgr_pLedDerPwrA_Ch2_Alt_B ;
extern const uint8 ParaMgr_pLedDerPwrA_Ch3_B ;
extern const uint8 ParaMgr_pLedDerPwrA_Ch4_B ;
extern const uint8 ParaMgr_pLedDerPwrB_Ch1_B;
extern const uint8 ParaMgr_pLedDerPwrB_Ch1_Tap_B;
extern const uint8 ParaMgr_pLedDerPwrB_Ch2_B ;
extern const uint8 ParaMgr_pLedDerPwrB_Ch2_Alt_B ;
extern const uint8 ParaMgr_pLedDerPwrB_Ch3_B ;
extern const uint8 ParaMgr_pLedDerPwrB_Ch4_B ;
extern const uint8 ParaMgr_pLedDerPwrC_Ch1_B ;
extern const uint8 ParaMgr_pLedDerPwrC_Ch1_Tap_B ;
extern const uint8 ParaMgr_pLedDerPwrC_Ch2_B ;
extern const uint8 ParaMgr_pLedDerPwrC_Ch2_Alt_B ;
extern const uint8 ParaMgr_pLedDerPwrC_Ch3_B ;
extern const uint8 ParaMgr_pLedDerPwrC_Ch4_B ;
extern const uint8 ParaMgr_pHSD1OLEnable_B;
extern const uint8 ParaMgr_pHSD2OLEnable_B;
extern const uint8 ParaMgr_pHSD1OLEnable_HW_Out1_B;
extern const uint8 ParaMgr_pHSD1OLEnable_HW_Out2_B;
extern const uint8 ParaMgr_pHSD1IOutOC_B ;
extern const uint8 ParaMgr_pHSD2IOutOC_B ;
extern const uint8 ParaMgr_pIOutOCHSD_HW_Out1_B ;
extern const uint8 ParaMgr_pIOutOCHSD_HW_Out2_B ;
extern const uint16 ParaMgr_pIOutSCGHSD1_W ;
extern const uint16 ParaMgr_pIOutSCGHSD2_W ;
extern const uint16 ParaMgr_pIOutSCGHSD_HW_Out1_W ;
extern const uint16 ParaMgr_pIOutSCGHSD_HW_Out2_W ;
extern const uint8 ParaMgr_pHSD1MaxVolt_B ;
extern const uint8 ParaMgr_pHSD2MaxVolt_B ;
extern const uint8 ParaMgr_pHSDMaxVolt_HW_Out1_B ;
extern const uint8 ParaMgr_pHSDMaxVolt__HW_Out2_B ;
extern const uint8 ParaMgr_pHSD1MinVolt_B ;
extern const uint8 ParaMgr_pHSD2MinVolt_B ;
extern const uint8 ParaMgr_pHSDMinVolt_HW_Out1_B ;
extern const uint8 ParaMgr_pHSDMinVolt_HW_Out2_B ;
extern const uint8 ParaMgr_pLedDerMinCurrLoBeamFlat_B ;
extern const uint8 ParaMgr_pLedDerMinCurrDirIndcr_B ;
extern const uint8 ParaMgr_pLedDerTempHys_B;
extern const uint8 ParaMgr_pNtcType_1_B;
extern const uint8 ParaMgr_pNtcType_2_B;
extern const uint8 ParaMgr_pNtcType_3_B;
extern const uint8 ParaMgr_pNtcType_4_B;
extern const uint8 ParaMgr_pNtcType_5_B;
extern const uint8 ParaMgr_pNtcType_6_B;
extern const uint8 ParaMgr_pNtcFaultTemp_1_B ;
extern const uint8 ParaMgr_pNtcFaultTemp_2_B ;
extern const uint8 ParaMgr_pNtcFaultTemp_3_B ;
extern const uint8 ParaMgr_pNtcFaultTemp_4_B ;
extern const uint8 ParaMgr_pNtcFaultTemp_5_B ;
extern const uint8 ParaMgr_pNtcFaultTemp_6_B ;
extern const uint8 ParaMgr_pLedChToNtc_Ch1_B ;
extern const uint8 ParaMgr_pLedChToNtc_Ch1_Tap_B ;
extern const uint8 ParaMgr_pLedChToNtc_Ch2_B ;
extern const uint8 ParaMgr_pLedChToNtc_Ch2_Alt_B ;
extern const uint8 ParaMgr_pLedChToNtc_Ch3_B ;
extern const uint8 ParaMgr_pLedChToNtc_Ch4_B ;
extern const uint32 ParaMgr_NTCType1_DW[160] ;
extern const uint32 ParaMgr_NTCType2_DW[160] ;
extern const uint8 ParaMgr_pRcodEnable_B;
extern const uint8 ParaMgr_pBinSrcCh_Ch1_B;
extern const uint8 ParaMgr_pBinSrcCh_Ch1_Tap_B;
extern const uint8 ParaMgr_pBinSrcCh_Ch2_B;
extern const uint8 ParaMgr_pBinSrcCh_Ch2_Alt_B;
extern const uint8 ParaMgr_pBinSrcCh_Ch3_B;
extern const uint8 ParaMgr_pBinSrcCh_Ch4_B;
extern const uint8 ParaMgr_pDefaultRcodIndexCh_Ch1_B;
extern const uint8 ParaMgr_pDefaultRcodIndexCh_Ch1_Tap_B;
extern const uint8 ParaMgr_pDefaultRcodIndexCh_Ch2_B;
extern const uint8 ParaMgr_pDefaultRcodIndexCh_Ch2_Alt_B;
extern const uint8 ParaMgr_pDefaultRcodIndexCh_Ch3_B;
extern const uint8 ParaMgr_pDefaultRcodIndexCh_Ch4_B;
extern const uint8 ParaMgr_pBinRcod1NTC_B;
extern const uint8 ParaMgr_pBinRcod2NTC_B;
extern const uint8 ParaMgr_pBinRcod3NTC_B;
extern const uint16 ParaMgr_pCodeRefFieldL_1_W ;
extern const uint16 ParaMgr_pCodeRefFieldH_1_W  ;
extern const uint16 ParaMgr_pCodeLedCurrent1_1_W ;
extern const uint16 ParaMgr_pCodeLedCurrent2_1_W ;
extern const uint16 ParaMgr_pCodeLedCurrent3_1_W ;
extern const uint16 ParaMgr_pCodeRefFieldL_2_W  ;
extern const uint16 ParaMgr_pCodeRefFieldH_2_W  ;
extern const uint16 ParaMgr_pCodeLedCurrent1_2_W ;
extern const uint16 ParaMgr_pCodeLedCurrent2_2_W ;
extern const uint16 ParaMgr_pCodeLedCurrent3_2_W ;
extern const uint16 ParaMgr_pCodeRefFieldL_3_W  ;
extern const uint16 ParaMgr_pCodeRefFieldH_3_W  ;
extern const uint16 ParaMgr_pCodeLedCurrent1_3_W ;
extern const uint16 ParaMgr_pCodeLedCurrent2_3_W ;
extern const uint16 ParaMgr_pCodeLedCurrent3_3_W ;
extern const uint16 ParaMgr_pCodeRefFieldL_4_W  ;
extern const uint16 ParaMgr_pCodeRefFieldH_4_W  ;
extern const uint16 ParaMgr_pCodeLedCurrent1_4_W ;
extern const uint16 ParaMgr_pCodeLedCurrent2_4_W ;
extern const uint16 ParaMgr_pCodeLedCurrent3_4_W ;
extern const uint16 ParaMgr_pCodeRefFieldL_5_W  ;
extern const uint16 ParaMgr_pCodeRefFieldH_5_W  ;
extern const uint16 ParaMgr_pCodeLedCurrent1_5_W ;
extern const uint16 ParaMgr_pCodeLedCurrent2_5_W ;
extern const uint16 ParaMgr_pCodeLedCurrent3_5_W ;
extern const uint16 ParaMgr_pCodeRefFieldL_6_W  ;
extern const uint16 ParaMgr_pCodeRefFieldH_6_W  ;
extern const uint16 ParaMgr_pCodeLedCurrent1_6_W ;
extern const uint16 ParaMgr_pCodeLedCurrent2_6_W ;
extern const uint16 ParaMgr_pCodeLedCurrent3_6_W ;
extern const uint16 ParaMgr_pCodeRefFieldL_7_W  ;
extern const uint16 ParaMgr_pCodeRefFieldH_7_W  ;
extern const uint16 ParaMgr_pCodeLedCurrent1_7_W ;
extern const uint16 ParaMgr_pCodeLedCurrent2_7_W ;
extern const uint16 ParaMgr_pCodeLedCurrent3_7_W ;
extern const uint16 ParaMgr_pCodeRefFieldL_8_W  ;
extern const uint16 ParaMgr_pCodeRefFieldH_8_W  ;
extern const uint16 ParaMgr_pCodeLedCurrent1_8_W ;
extern const uint16 ParaMgr_pCodeLedCurrent2_8_W ;
extern const uint16 ParaMgr_pCodeLedCurrent3_8_W ;
extern const uint16 ParaMgr_pCodeRefFieldL_9_W  ;
extern const uint16 ParaMgr_pCodeRefFieldH_9_W  ;
extern const uint16 ParaMgr_pCodeLedCurrent1_9_W ;
extern const uint16 ParaMgr_pCodeLedCurrent2_9_W ;
extern const uint16 ParaMgr_pCodeLedCurrent3_9_W ;
extern const uint16 ParaMgr_pCodeRefFieldL_10_W  ;
extern const uint16 ParaMgr_pCodeRefFieldH_10_W  ;
extern const uint16 ParaMgr_pCodeLedCurrent1_10_W ;
extern const uint16 ParaMgr_pCodeLedCurrent2_10_W ;
extern const uint16 ParaMgr_pCodeLedCurrent3_10_W ;
extern const uint16 ParaMgr_pFanToChannel_W;
extern const uint16 ParaMgr_pFanOnLedCh_W;
extern const uint16 ParaMgr_pFanSupInrushTime_W  ;
extern const uint16 ParaMgr_pFanNomCurrent_W;
extern const uint8 ParaMgr_pFanNomCurTol_B ;
extern const uint16 ParaMgr_pFanLockDebTime_W  ;
extern const uint8 ParaMgr_pFanLockProtOnTime0_B;
extern const uint8 ParaMgr_pFanLockProtTimeTol0_B ;
extern const uint8 ParaMgr_pFanLockRetryOffTime_B;
extern const uint8 ParaMgr_pFanFaultSignal_B;
extern const uint8 ParaMgr_pFanLedTempHys_B;
extern const uint8 ParaMgr_pFanCoolLedTempLo_B ;
extern const uint8 ParaMgr_pFanCoolLedTempHi_B ;
extern const uint8 ParaMgr_pFanCoolPowerLo_B ;
extern const uint8 ParaMgr_pFanCoolPowerHi_B ;
extern const uint8 ParaMgr_pFanNumber_B ;
extern const uint8 ParaMgr_pFanControlPinl_B ;
extern const uint8 ParaMgr_pFanDiagInputType_B ;
extern const uint8 ParaMgr_pVehLvLType_B;
extern const uint8 ParaMgr_pAHBCTyp_B;
extern const uint8 ParaMgr_pDCMotrCntrlSCG_B;
extern const uint8 ParaMgr_pDCMotrCntrlSCB_B ;
extern const uint16 ParaMgr_pIOutStallDCMotrHSD_W ;
extern const uint8 ParaMgr_pManLvlDCPos1_B ;
extern const uint8 ParaMgr_pManLvlDCPos2_B ;
extern const uint8 ParaMgr_pManLvlDCPos3_B ;
extern const uint8 ParaMgr_pManLvlDCPos4_B ;
extern const uint8 ParaMgr_pManLvlDCPos5_B ;
extern const uint8 ParaMgr_pLVLSafetyPosDC_B ;
extern const uint8 ParaMgr_pDCMotrCntrlLowrThd_B ;
extern const uint8 ParaMgr_pDCMotrCntrlUpprThd_B ;
extern const uint16 ParaMgr_pDCMotrDeactDlyTi_W  ;
extern const uint8 ParaMgr_pDCMotorReserve1_B;
extern const uint8 ParaMgr_pDCMotorReserve2_B;
extern const uint8 ParaMgr_pDCMotorReserve3_B;
extern const uint8 ParaMgr_pDCMotorReserve4_B;
extern const uint16 ParaMgr_pAHBCDistOfHiBeam_W ;
extern const uint16 ParaMgr_pLedLoBeamOnRampTi_W ;
extern const uint16 ParaMgr_pLedHiBeamOnRampTi_W;
extern const uint16 ParaMgr_pLedPosLiOnRampTi_W ;
extern const uint16 ParaMgr_pLedFogLiOnRampTi_W;
extern const uint16 ParaMgr_pLedDRLOnRampTi_W ;
extern const uint16 ParaMgr_pLedDirIndcrOnRampTi_W;
extern const uint16 ParaMgr_pLedCornrgOnRampTi_W;
extern const uint16 ParaMgr_pLedLogoLiOnRampTi_W;
extern const uint16 ParaMgr_pLedFrntCrossLiOnRampTi_W;
extern const uint16 ParaMgr_pLedGrilleLiOnRampTi_W;
extern const uint16 ParaMgr_pLedLoBeamOFFRampTi_W ;
extern const uint16 ParaMgr_pLedHiBeamOFFRampTi_W;
extern const uint16 ParaMgr_pLedPosLiOFFRampTi_W ;
extern const uint16 ParaMgr_pLedFogLiOFFRampTi_W;
extern const uint16 ParaMgr_pLedDRLOFFRampTi_W ;
extern const uint16 ParaMgr_pLedDirIndcrOFFRampTi_W;
extern const uint16 ParaMgr_pLedCornrgOFFRampTi_W;
extern const uint16 ParaMgr_pLedLogoLiOFFRampTi_W;
extern const uint16 ParaMgr_pLedFrntCrossLiOFFRampTi_W;
extern const uint16 ParaMgr_pLedGrilleLiOFFRampTi_W;
extern const uint8 ParaMgr_pLedLoBeamOnDelay_B;
extern const uint8 ParaMgr_pLedHiBeamOnDelay_B;
extern const uint8 ParaMgr_pLedPosOnDelay_B;
extern const uint8 ParaMgr_pLedFogOnDelay_B;
extern const uint8 ParaMgr_pLedDRLOnDelay_B;
extern const uint8 ParaMgr_LeLamp_pLedDirIndcrBeamOnDelayLe_B;
extern const uint8 ParaMgr_RiLamp_pLedDirIndcrBeamOnDelayRi_B;
extern const uint8 ParaMgr_pLedCornrgOnDelay_B;
extern const uint8 ParaMgr_pLedLogoOnDelay_B;
extern const uint8 ParaMgr_pLedFrntCrossOnDelay_B;
extern const uint8 ParaMgr_pLedGrilleOnDelay_B;
extern const uint8 ParaMgr_pLedLoBeamOFFDelay_B;
extern const uint8 ParaMgr_pLedHiBeamOFFDelay_B;
extern const uint8 ParaMgr_pLedPosOFFDelay_B;
extern const uint8 ParaMgr_pLedFogOFFDelay_B;
extern const uint8 ParaMgr_pLedDRLOFFDelay_B;
extern const uint8 ParaMgr_LeLamp_pLedDirIndcrBeamOFFDelayLe_B;
extern const uint8 ParaMgr_RiLamp_pLedDirIndcrBeamOFFDelayRi_B;
extern const uint8 ParaMgr_pLedCornrgOFFDelay_B;
extern const uint8 ParaMgr_pLedLogoOFFDelay_B;
extern const uint8 ParaMgr_pLedFrntCrossOFFDelay_B;
extern const uint8 ParaMgr_pLedGrilleOFFDelay_B;
extern const uint8 ParaMgr_pLedSeqTiHwl_B;
extern const uint16 ParaMgr_pLedTimeUpPosTi_W ;
extern const uint8 ParaMgr_pLedIntensityPos_B ;
extern const uint8 ParaMgr_pLedIntensityPosTi_B;
extern const uint16 ParaMgr_pLedTimeUpDrlTi_W ;
extern const uint8 ParaMgr_pLedIntensityDrlTi_B;
extern const uint8 ParaMgr_pLedIntensityDrlTi40mm_B;
extern const uint8 ParaMgr_pWelGbytyp_B;
extern const uint8 ParaMgr_pWelDlyTi_B ;
extern const uint8 ParaMgr_pGbyDlyTi_B ;
extern const uint8 ParaMgr_pLedPosIntWelGby_B ;
extern const uint8 ParaMgr_pLEDPosDRLType_B ;
extern const uint16 ParaMgr_pFssLostComTime_W ;
extern const uint8 ParaMgr_pFrntCrossAvl_B ;
extern const uint8 ParaMgr_pGrilleAvl_B ;
extern const uint8 ParaMgr_pLedGamma_B ;
extern const uint8 ParaMgr_pWelcomP1G1ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP1G1OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP1G2ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP1G2OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP1G3ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP1G3OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP1G4ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP1G4OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP1G5ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP1G5OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP1G6ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP1G6OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP1G7ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP1G7OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP1G8ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP1G8OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP2G1ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP2G1OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP2G2ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP2G2OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP2G3ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP2G3OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP2G4ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP2G4OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP2G5ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP2G5OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP2G6ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP2G6OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP2G7ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP2G7OffTiConTiUpBri_B[30]  ;
extern const uint8 ParaMgr_pWelcomP2G8ModeLowBri_B[20]  ;
extern const uint8 ParaMgr_pWelcomP2G8OffTiConTiUpBri_B[30]  ;
#endif



