/*******************************************************************************
**                                                                            **
** Copyright (C) iSOFT   (2016)                                               **
**                                                                            **
** All rights reserved.                                                       **
**                                                                            **
** This document contains proprietary information belonging to iSOFT.         **
** Passing on and copying of this document, and communication                 **
** of its contents is not permitted without prior written authorization.      **
**                                                                            **
********************************************************************************
**                                                                            **
**  FILENAME    : BswM_Cfg.h                                                  **
**                                                                            **
**  Created on  :                                                             **
**  Author      : stanleyluo                                                  **
**  Vendor      :                                                             **
**  DESCRIPTION : BswM pre-compile configuration MACROs                       **
**                                                                            **
**  SPECIFICATION(S) :   AUTOSAR classic Platform 4.2.2                       **
**                                                                            **
*******************************************************************************/


/*******************************************************************************
**                      Revision Control History                              **
*******************************************************************************/


#ifndef BSWM_CFG_H
#define BSWM_CFG_H

/*******************************************************************************
**                      Include Section                                       **
*******************************************************************************/
#include "Std_Types.h"
/*******************************************************************************
**                      Global Symbols                                        **
*******************************************************************************/
/*BswMDevErrorDetect*/
#define BSWM_DEV_ERROR_DETECT				STD_OFF 

/*BswMCanSMEnabled*/
#define BSWM_CANSM_ENABLED					STD_OFF

/*BswMCanSMIcomEnabled*/
#define BSWM_CANSM_ICOM_ENABLED				STD_OFF

/*BswMComMEnabled*/
#define BSWM_COMM_ENABLED					STD_ON

/*BswMDcmEnabled*/
#define BSWM_DCM_ENABLED					STD_ON

/*BswMEcuMEnabled*/
#define BSWM_ECUM_ENABLED					STD_ON

/*BswMEthSMEnabled*/
#define BSWM_ETHSM_ENABLED					STD_OFF

/*BswMFrSMEnabled*/
#define BSWM_FRSM_ENABLED					STD_OFF

/*BswMGenericRequestEnabled*/
#define BSWM_GENERIC_REQUEST_ENABLED		STD_ON

/*BswMJ1939DcmEnabled*/
#define  BSWM_J1939DCM_ENABLED				STD_OFF

/*BswMJ1939NmEnabled*/
#define BSWM_J1939NM_ENABLED				STD_OFF

/*BswMJ1939RmEnabled, calculated according to the action existence*/
#define BSWM_J1939RM_ENABLED               	STD_OFF       /* create J1939Rm */

/*BswMNMEnabled, calculated according to the request port and action existence*/
#define BSWM_NM_ENABLED                    	STD_OFF            /* create Nm */

/*BswMComEnabled, calculated according to the action existence*/
#define BSWM_COM_ENABLED                   	STD_OFF             /* create Com */

/*BswMRteEnabled, calculated according to the SWC RTE request port and action existence*/
#define BSWM_RTE_ENABLED                   	STD_OFF/* create Rte */         

/*BswMPduREnabled, calculated according to the action existence*/
#define BSWM_PDUR_ENABLED                  STD_OFF          /* create Pdur */

/*BswMLinSMEnabled*/
#define BSWM_LINSM_ENABLED					STD_ON

/*BswMLinTPEnabled*/
#define BSWM_LINTP_ENABLED					STD_OFF

/*BswMNvMEnabled*/
#define BSWM_NVM_ENABLED					STD_OFF

/*BswMSchMEnabled*/
#define BSWM_SCHM_ENABLED					STD_OFF 

/*BswMSdEnabled*/
#define BSWM_SD_ENABLED						STD_OFF

/*BswMVersionInfoApi*/
#define BSWM_VERSION_INFO_API				STD_ON

/*BswMWdgMEnabled*/
#define BSWM_WDGM_ENABLED					STD_OFF

/**********COSNTANTS generated by pre-compile configuration*************/
/*Total number of cores which running AUTOSAR BSW*/
#define BSWM_MAX_NUM_CORE                   1

/*Total number of partitions which running AUTOSAR*/
#define BSWM_MAX_NUM_PARTITION              1

/*Total number of Rules per partition*/
#define BSWM_MAX_NUM_RULES_PER_PARTITION    18


#endif /* BSWM_CFG_H */
